name: Zip Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Zip Files
      uses: TheDoctor0/zip-release@0.4.1
      with:
        filename: 'fvtt-countdowns.zip'
        exclusions: '*.git*'
